### PR TITLE
WA15 protocol changes

### PR DESCRIPTION
**Pull request by CODeRUS**
And my personal additions to login process.
Not tested on N900, please do it before merging.

### CODE REVIEW

**Comment by turanmahmudov** [comment]
doesn't authorize now

sending streamStart to "s.whatsapp.net" "S40-2.12.68-443"
"OUTGOING:

stream:features
    <groups_v2 />
    <presence />
    <privacy />
    <readreceipts />
/stream:features"
"OUTGOING:

<auth mechanism="WAUTH-2" passive="false" user="994703226406" />"
"OUTGOING:

<iq id="config_1" to="s.whatsapp.net" type="set">
    <config lc="US" lg="en" platform="none" xmlns="urn:xmpp:whatsapp:push" />
</iq>"
126  bytes written...
"OUTGOING:

<presence name="Turan Mahmudov" />"
23  bytes written...

**Comment by CODeRUS** [comment]
use code tags please

**Comment by CODeRUS** [comment]
or better paste your log to gist and post link here

**Comment by CODeRUS** [comment]
working? :)

**Pull request merged**
